name: amazon_like_filter
description: 'AmazonLikeFilter is an widget that is used to build Filter UI like as amazon app.'
version: 1.0.0
homepage: https://github.com/subhashDev11/amazon_like_filter

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

screenshots:
  - description: 'Example of the flutter amazon like filter widget.'
    path: example/assets/filter_shot.png